/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PanelsuratKeteranganTidakBerijazah.java
 *
 * Created on Jul 23, 2012, 2:40:45 PM
 */
package fauzi.project.panelSurat;

import fauzi.project.jenisSurat.suratkettidakijazah;
import java.text.SimpleDateFormat;

/**
 *
 * @author fauzi
 */
public class PanelsuratKeteranganTidakBerijazah extends javax.swing.JPanel {

    /** Creates new form PanelsuratKeteranganTidakBerijazah */
    public PanelsuratKeteranganTidakBerijazah() {
        initComponents();
    }
    
    //public SimpleDa
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAtas = new javax.swing.JPanel();
        panelTengah = new javax.swing.JPanel();
        txttglSurat = new com.toedter.calendar.JDateChooser();
        txttgllahir = new com.toedter.calendar.JDateChooser();
        flabel1 = new fauzi.project.swingResource.Flabel();
        flabel2 = new fauzi.project.swingResource.Flabel();
        txtkode = new fauzi.project.panelSurat.FtextBox();
        txtnama = new fauzi.project.panelSurat.FtextBox();
        flabel3 = new fauzi.project.swingResource.Flabel();
        txttempatlahir = new fauzi.project.panelSurat.FtextBox();
        flabel5 = new fauzi.project.swingResource.Flabel();
        flabel6 = new fauzi.project.swingResource.Flabel();
        txtpekerjaa = new fauzi.project.panelSurat.FtextBox();
        flabel8 = new fauzi.project.swingResource.Flabel();
        flabel9 = new fauzi.project.swingResource.Flabel();
        flabel10 = new fauzi.project.swingResource.Flabel();
        txtalamat = new fauzi.project.panelSurat.FtextBox();
        flabel11 = new fauzi.project.swingResource.Flabel();
        txtnamabapak = new fauzi.project.panelSurat.FtextBox();
        flabel12 = new fauzi.project.swingResource.Flabel();
        cmbStaatus = new javax.swing.JComboBox();
        txtkades1 = new fauzi.project.panelSurat.FtextBox();
        flabel13 = new fauzi.project.swingResource.Flabel();
        txttahun = new fauzi.project.panelSurat.FtextBox();
        flabel14 = new fauzi.project.swingResource.Flabel();
        panelBawah = new javax.swing.JPanel();
        btgenerate = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        panelAtas.setLayout(new java.awt.BorderLayout());
        add(panelAtas, java.awt.BorderLayout.PAGE_START);

        panelTengah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelTengah.add(txttglSurat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 300, 30));
        panelTengah.add(txttgllahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 300, 30));

        flabel1.setText("Surat Keterangan Tidak Berijazah");
        panelTengah.add(flabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        flabel2.setText("Kode Surat :");
        panelTengah.add(flabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));
        panelTengah.add(txtkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 300, -1));
        panelTengah.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 300, -1));

        flabel3.setText("Nama :");
        panelTengah.add(flabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));
        panelTengah.add(txttempatlahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 300, -1));

        flabel5.setText("Tempat Lahir :");
        panelTengah.add(flabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        flabel6.setText("Tanggal Lahir :");
        panelTengah.add(flabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));
        panelTengah.add(txtpekerjaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 300, -1));

        flabel8.setText("Pekerjaan :");
        panelTengah.add(flabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        flabel9.setText("Status Kawin :");
        panelTengah.add(flabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        flabel10.setText("Alamat :");
        panelTengah.add(flabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));
        panelTengah.add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 300, -1));

        flabel11.setText("Tanggal Surat :");
        panelTengah.add(flabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, -1, -1));
        panelTengah.add(txtnamabapak, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 300, -1));

        flabel12.setText("Nama Bapak :");
        panelTengah.add(flabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        cmbStaatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Menikah", "Single", "Janda", "Duda" }));
        panelTengah.add(cmbStaatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 300, 30));
        panelTengah.add(txtkades1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 300, -1));

        flabel13.setText("Kepala Desa :");
        panelTengah.add(flabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));
        panelTengah.add(txttahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 300, -1));

        flabel14.setText("Tahun :");
        panelTengah.add(flabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        add(panelTengah, java.awt.BorderLayout.CENTER);

        panelBawah.setLayout(new java.awt.BorderLayout());

        btgenerate.setText("Generate");
        btgenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btgenerateActionPerformed(evt);
            }
        });
        panelBawah.add(btgenerate, java.awt.BorderLayout.CENTER);

        add(panelBawah, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents
    public String getKode(){
        return txtkode.getText();
    }
    
    public String getNama(){
        return txtnama.getText();
    }
    
    public String getTempatLahir(){
        return txttempatlahir.getText();
    }
    
    public String getTanggalLahir(){
    String tgl = null;
        if(txttgllahir.getDate()!=null){
            SimpleDateFormat ganti=new SimpleDateFormat("dd-MM-yyyy");
        tgl=ganti.format(txttgllahir.getDate());
        }
    return tgl;
    }
        
    public String getStatus(){
        return cmbStaatus.getSelectedItem().toString();
    }
            
    public String getPekerjaan(){
        return txtpekerjaa.getText();
    }
        
    public String getNamaBapak(){
        return txtnamabapak.getText();
    }
           
    public String getAlamat(){
        return txtalamat.getText();
    }
    
    public String getKades(){
        return txtnamabapak.getText();
    }
    
    public String getTanggalSurat(){
        String tgl = null;
        if(txttglSurat.getDate()!=null){
            SimpleDateFormat ganti=new SimpleDateFormat("dd-MM-yyyy");
            tgl=ganti.format(txttglSurat.getDate());
        }
    return tgl;        
    }
    
    public String getTahun(){
        return txttahun.getText();
    }
    
    private void btgenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btgenerateActionPerformed
        // TODO add your handling code here:
        suratkettidakijazah sktb = new suratkettidakijazah(getKode(), getNama(), getTempatLahir(), getTanggalLahir(), getPekerjaan(), getStatus(), getNamaBapak(), getAlamat(), getKades(), getTahun(), getTanggalSurat());
    }//GEN-LAST:event_btgenerateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btgenerate;
    private javax.swing.JComboBox cmbStaatus;
    private fauzi.project.swingResource.Flabel flabel1;
    private fauzi.project.swingResource.Flabel flabel10;
    private fauzi.project.swingResource.Flabel flabel11;
    private fauzi.project.swingResource.Flabel flabel12;
    private fauzi.project.swingResource.Flabel flabel13;
    private fauzi.project.swingResource.Flabel flabel14;
    private fauzi.project.swingResource.Flabel flabel2;
    private fauzi.project.swingResource.Flabel flabel3;
    private fauzi.project.swingResource.Flabel flabel5;
    private fauzi.project.swingResource.Flabel flabel6;
    private fauzi.project.swingResource.Flabel flabel8;
    private fauzi.project.swingResource.Flabel flabel9;
    private javax.swing.JPanel panelAtas;
    private javax.swing.JPanel panelBawah;
    private javax.swing.JPanel panelTengah;
    private fauzi.project.panelSurat.FtextBox txtalamat;
    private fauzi.project.panelSurat.FtextBox txtkades1;
    private fauzi.project.panelSurat.FtextBox txtkode;
    private fauzi.project.panelSurat.FtextBox txtnama;
    private fauzi.project.panelSurat.FtextBox txtnamabapak;
    private fauzi.project.panelSurat.FtextBox txtpekerjaa;
    private fauzi.project.panelSurat.FtextBox txttahun;
    private fauzi.project.panelSurat.FtextBox txttempatlahir;
    private com.toedter.calendar.JDateChooser txttglSurat;
    private com.toedter.calendar.JDateChooser txttgllahir;
    // End of variables declaration//GEN-END:variables
}
