/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * suratKeteranganKelakuanBaik.java
 *
 * Created on Jul 23, 2012, 2:40:45 PM
 */
package fauzi.project.panelSurat;

import docgen.suratKtpSementara;
import java.text.SimpleDateFormat;

/**
 *
 * @author fauzi
 */
public class PanelSuratKeterangan extends javax.swing.JPanel {

    /** Creates new form suratKeteranganKelakuanBaik */
    public PanelSuratKeterangan() {
        initComponents();
    }
    
    //public SimpleDa
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAtas = new javax.swing.JPanel();
        panelTengah = new javax.swing.JPanel();
        cmbagama = new javax.swing.JComboBox();
        cmbjkel = new javax.swing.JComboBox();
        txttglsurat = new com.toedter.calendar.JDateChooser();
        txttgllahir = new com.toedter.calendar.JDateChooser();
        flabel1 = new fauzi.project.swingResource.Flabel();
        flabel2 = new fauzi.project.swingResource.Flabel();
        txtkode = new fauzi.project.panelSurat.FtextBox();
        txtnama = new fauzi.project.panelSurat.FtextBox();
        flabel3 = new fauzi.project.swingResource.Flabel();
        flabel4 = new fauzi.project.swingResource.Flabel();
        txttempatlahir = new fauzi.project.panelSurat.FtextBox();
        flabel5 = new fauzi.project.swingResource.Flabel();
        flabel6 = new fauzi.project.swingResource.Flabel();
        flabel7 = new fauzi.project.swingResource.Flabel();
        txtpekerjaa = new fauzi.project.panelSurat.FtextBox();
        flabel8 = new fauzi.project.swingResource.Flabel();
        flabel10 = new fauzi.project.swingResource.Flabel();
        txtalamat = new fauzi.project.panelSurat.FtextBox();
        flabel11 = new fauzi.project.swingResource.Flabel();
        txttujuan = new fauzi.project.panelSurat.FtextBox();
        flabel12 = new fauzi.project.swingResource.Flabel();
        flabel13 = new fauzi.project.swingResource.Flabel();
        cmbStatus = new javax.swing.JComboBox();
        txttahun = new fauzi.project.panelSurat.FtextBox();
        flabel14 = new fauzi.project.swingResource.Flabel();
        flabel15 = new fauzi.project.swingResource.Flabel();
        txtkades1 = new fauzi.project.panelSurat.FtextBox();
        panelBawah = new javax.swing.JPanel();
        btgenerate = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        panelAtas.setLayout(new java.awt.BorderLayout());
        add(panelAtas, java.awt.BorderLayout.PAGE_START);

        panelTengah.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbagama.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Islam", "Kristen", "Katolik", "Hindu", "Budha", "Kong Hu Chu" }));
        panelTengah.add(cmbagama, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 290, 30));

        cmbjkel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laki- Laki", "Perempuan" }));
        panelTengah.add(cmbjkel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 290, 30));
        panelTengah.add(txttglsurat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 290, 30));
        panelTengah.add(txttgllahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 290, 30));

        flabel1.setText("Surat Keterangan");
        panelTengah.add(flabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, -1));

        flabel2.setText("Kode Surat :");
        panelTengah.add(flabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));
        panelTengah.add(txtkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 300, -1));
        panelTengah.add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 300, -1));

        flabel3.setText("Nama :");
        panelTengah.add(flabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        flabel4.setText("Agama :");
        panelTengah.add(flabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));
        panelTengah.add(txttempatlahir, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 300, -1));

        flabel5.setText("Tempat Lahir :");
        panelTengah.add(flabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, -1));

        flabel6.setText("Tanggal Lahir :");
        panelTengah.add(flabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, -1, -1));

        flabel7.setText("Jenis Kelamin :");
        panelTengah.add(flabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, -1, -1));
        panelTengah.add(txtpekerjaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 300, -1));

        flabel8.setText("Pekerjaan :");
        panelTengah.add(flabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        flabel10.setText("Alamat :");
        panelTengah.add(flabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));
        panelTengah.add(txtalamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 410, 300, -1));

        flabel11.setText("Tanggal Surat :");
        panelTengah.add(flabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, -1, -1));
        panelTengah.add(txttujuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, 300, -1));

        flabel12.setText("Kepala Desa :");
        panelTengah.add(flabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        flabel13.setText("Status :");
        panelTengah.add(flabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Menikah", "Belum Menikah", "Janda", "Duda" }));
        panelTengah.add(cmbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 290, 30));
        panelTengah.add(txttahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 300, -1));

        flabel14.setText("Tahun :");
        panelTengah.add(flabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        flabel15.setText("Tujuan :");
        panelTengah.add(flabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, -1, -1));
        panelTengah.add(txtkades1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 300, -1));

        add(panelTengah, java.awt.BorderLayout.CENTER);

        panelBawah.setLayout(new java.awt.BorderLayout());

        btgenerate.setText("Generate");
        btgenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btgenerateActionPerformed(evt);
            }
        });
        panelBawah.add(btgenerate, java.awt.BorderLayout.CENTER);

        add(panelBawah, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>//GEN-END:initComponents
    public String getKode(){
        return txtkode.getText();
    }
    
    public String getNama(){
        return txtnama.getText();
    }
    
    public String getTempatLahir(){
        return txttempatlahir.getText();
    }
    
    public String getTanggalLahir(){
    String tgl = null;
        if(txttgllahir.getDate()!=null){
            SimpleDateFormat ganti=new SimpleDateFormat("dd-MM-yyyy");
        tgl=ganti.format(txttgllahir.getDate());
        }
    return tgl;
    }
    
    public String getJenisKelamin(){
        return cmbjkel.getSelectedItem().toString();
    }
    
    public String getAgama(){
        return cmbagama.getSelectedItem().toString();
    }
    
    public String getStatus(){       
        return cmbStatus.getSelectedItem().toString();
    }
    
    public String getPekerjaan(){
        return txtpekerjaa.getText();
    }    
    
    public String getAlamat(){
        return txtalamat.getText();
    }
    
    public String getKades(){
        return txttujuan.getText();
    }
    
    public String getTanggalSurat(){
        String tgl = null;
        if(txttglsurat.getDate()!=null){
            SimpleDateFormat ganti=new SimpleDateFormat("dd-MM-yyyy");
            tgl=ganti.format(txttglsurat.getDate());
        }
    return tgl;        
    }
    
    public String getTahun(){
        return txttahun.getText();
    }
    
    public String getTujuan(){
        return txttujuan.getText();
    }    
    
    private void btgenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btgenerateActionPerformed
        // TODO add your handling code here:
        suratKtpSementara sktps = new suratKtpSementara(getKode(), getNama(), getTempatLahir(), getTanggalSurat(), getJenisKelamin(), getAgama(), getStatus(), getPekerjaan(), getAlamat(), getKades(), getTahun(), getTujuan(), getTanggalSurat());
    }//GEN-LAST:event_btgenerateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btgenerate;
    private javax.swing.JComboBox cmbStatus;
    private javax.swing.JComboBox cmbagama;
    private javax.swing.JComboBox cmbjkel;
    private fauzi.project.swingResource.Flabel flabel1;
    private fauzi.project.swingResource.Flabel flabel10;
    private fauzi.project.swingResource.Flabel flabel11;
    private fauzi.project.swingResource.Flabel flabel12;
    private fauzi.project.swingResource.Flabel flabel13;
    private fauzi.project.swingResource.Flabel flabel14;
    private fauzi.project.swingResource.Flabel flabel15;
    private fauzi.project.swingResource.Flabel flabel2;
    private fauzi.project.swingResource.Flabel flabel3;
    private fauzi.project.swingResource.Flabel flabel4;
    private fauzi.project.swingResource.Flabel flabel5;
    private fauzi.project.swingResource.Flabel flabel6;
    private fauzi.project.swingResource.Flabel flabel7;
    private fauzi.project.swingResource.Flabel flabel8;
    private javax.swing.JPanel panelAtas;
    private javax.swing.JPanel panelBawah;
    private javax.swing.JPanel panelTengah;
    private fauzi.project.panelSurat.FtextBox txtalamat;
    private fauzi.project.panelSurat.FtextBox txtkades1;
    private fauzi.project.panelSurat.FtextBox txtkode;
    private fauzi.project.panelSurat.FtextBox txtnama;
    private fauzi.project.panelSurat.FtextBox txtpekerjaa;
    private fauzi.project.panelSurat.FtextBox txttahun;
    private fauzi.project.panelSurat.FtextBox txttempatlahir;
    private com.toedter.calendar.JDateChooser txttgllahir;
    private com.toedter.calendar.JDateChooser txttglsurat;
    private fauzi.project.panelSurat.FtextBox txttujuan;
    // End of variables declaration//GEN-END:variables
}
