/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mainFrame.java
 *
 * Created on Jul 23, 2012, 11:51:08 AM
 */
package fauzi.project.ELT27;

import com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel;
import com.sun.java.swing.plaf.windows.WindowsClassicLookAndFeel;
import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.plaf.metal.MetalLookAndFeel;

/**
 *
 * @author fauzi
 */
public class mainFrame extends javax.swing.JFrame {

    /** Creates new form mainFrame */
    public mainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAtas = new javax.swing.JPanel();
        flabel1 = new fauzi.project.swingResource.Flabel();
        cmbPil = new javax.swing.JComboBox();
        panelBawah = new javax.swing.JPanel();
        panelsuratKeteranganTidakBerijazah1 = new fauzi.project.panelSurat.PanelsuratKeteranganTidakBerijazah();
        panelsuratKeteranganKelakuanBaik1 = new fauzi.project.panelSurat.PanelsuratKeteranganKelakuanBaik();
        panelSuratKetKTPSementara1 = new fauzi.project.panelSurat.PanelSuratKetKTPSementara();
        panelSuratDomisili1 = new fauzi.project.panelSurat.PanelSuratDomisili();
        panelSuratketeranganKurangMampu1 = new fauzi.project.panelSurat.PanelSuratketeranganKurangMampu();
        panelSuratKeterangan1 = new fauzi.project.panelSurat.PanelSuratKeterangan();
        panelSuratRekomendasi1 = new fauzi.project.panelSurat.PanelSuratRekomendasi();
        panelSuratTugas1 = new fauzi.project.panelSurat.PanelSuratTugas();
        panelSuratsimdanKTP1 = new fauzi.project.panelSurat.PanelSuratsimdanKTP();
        panelSuratPernahNikah1 = new fauzi.project.panelSurat.PanelSuratPernahNikah();
        jMenuBar1 = new javax.swing.JMenuBar();
        file = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        metal = new javax.swing.JMenuItem();
        windows = new javax.swing.JMenuItem();
        winclass = new javax.swing.JMenuItem();
        nimbus = new javax.swing.JMenuItem();
        Credits = new javax.swing.JMenu();
        credit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Administrasi Surat Menyurat Desa Toronan");
        setResizable(false);

        panelAtas.setLayout(new java.awt.BorderLayout());

        flabel1.setText("Pilih Jenis Surat :");
        panelAtas.add(flabel1, java.awt.BorderLayout.PAGE_START);

        cmbPil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Surat Keterangan Tidak Berijazah", "Surat Keterangan Berkelakuan Baik", "Surat Keterangan KTP Sementara", "Surat Keterangan Domisili", "Surat Keterangan Kurang Mampu", "Surat Keterangan", "Surat Rekomendasi", "Surat Perintah Tugas", "Surat Keterangan Pengambilan KTP dan SIM", "Surat Keterangan Pernah Nikah" }));
        cmbPil.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPilItemStateChanged(evt);
            }
        });
        cmbPil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPilActionPerformed(evt);
            }
        });
        panelAtas.add(cmbPil, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(panelAtas, java.awt.BorderLayout.PAGE_START);

        panelBawah.setLayout(new java.awt.CardLayout());
        panelBawah.add(panelsuratKeteranganTidakBerijazah1, "0");
        panelBawah.add(panelsuratKeteranganKelakuanBaik1, "1");
        panelBawah.add(panelSuratKetKTPSementara1, "2");
        panelBawah.add(panelSuratDomisili1, "3");
        panelBawah.add(panelSuratketeranganKurangMampu1, "4");
        panelBawah.add(panelSuratKeterangan1, "5");
        panelBawah.add(panelSuratRekomendasi1, "6");
        panelBawah.add(panelSuratTugas1, "7");
        panelBawah.add(panelSuratsimdanKTP1, "8");
        panelBawah.add(panelSuratPernahNikah1, "9");

        getContentPane().add(panelBawah, java.awt.BorderLayout.CENTER);

        file.setText("File");

        jMenuItem1.setText("exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        file.add(jMenuItem1);

        jMenuBar1.add(file);

        jMenu1.setText("Tema");

        metal.setText("Metal");
        metal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                metalActionPerformed(evt);
            }
        });
        jMenu1.add(metal);

        windows.setText("Windows");
        windows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                windowsActionPerformed(evt);
            }
        });
        jMenu1.add(windows);

        winclass.setText("Windows Classic");
        winclass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                winclassActionPerformed(evt);
            }
        });
        jMenu1.add(winclass);

        nimbus.setText("Nimbus");
        nimbus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimbusActionPerformed(evt);
            }
        });
        jMenu1.add(nimbus);

        jMenuBar1.add(jMenu1);

        Credits.setText("Credits");

        credit.setText("Credits");
        credit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditActionPerformed(evt);
            }
        });
        Credits.add(credit);

        jMenuBar1.add(Credits);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbPilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPilActionPerformed
        // TODO add your handling code here:        
        CardLayout cl = (CardLayout) panelBawah.getLayout();
        cl.show(panelBawah, String.valueOf(cmbPil.getSelectedIndex()));
    }//GEN-LAST:event_cmbPilActionPerformed

    private void cmbPilItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPilItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPilItemStateChanged

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void metalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_metalActionPerformed
        // TODO add your handling code here:
        try{
            UIManager.setLookAndFeel(new MetalLookAndFeel());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "terjadi kesalahan pada look and feel manager");
        }
        finally{
            javax.swing.SwingUtilities.updateComponentTreeUI(this);
        }        
    }//GEN-LAST:event_metalActionPerformed

    private void windowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_windowsActionPerformed
        // TODO add your handling code here:
        try{
            UIManager.setLookAndFeel(new WindowsLookAndFeel());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "terjadi kesalahan pada look and feel manager");
        }
        finally{
            javax.swing.SwingUtilities.updateComponentTreeUI(this);
        }        
    }//GEN-LAST:event_windowsActionPerformed

    private void winclassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_winclassActionPerformed
        // TODO add your handling code here:
        try{
            UIManager.setLookAndFeel(new WindowsClassicLookAndFeel());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "terjadi kesalahan pada look and feel manager");
        }
        finally{
            javax.swing.SwingUtilities.updateComponentTreeUI(this);
        }        
    }//GEN-LAST:event_winclassActionPerformed

    private void nimbusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimbusActionPerformed
        // TODO add your handling code here:
        try{
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "terjadi kesalahan pada look and feel manager");
        }
        finally{
            javax.swing.SwingUtilities.updateComponentTreeUI(this);
        }        
    }//GEN-LAST:event_nimbusActionPerformed

    private void creditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditActionPerformed
        // TODO add your handling code here:
        new Credits().setVisible(true);
    }//GEN-LAST:event_creditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Credits;
    private javax.swing.JComboBox cmbPil;
    private javax.swing.JMenuItem credit;
    private javax.swing.JMenu file;
    private fauzi.project.swingResource.Flabel flabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem metal;
    private javax.swing.JMenuItem nimbus;
    private javax.swing.JPanel panelAtas;
    private javax.swing.JPanel panelBawah;
    private fauzi.project.panelSurat.PanelSuratDomisili panelSuratDomisili1;
    private fauzi.project.panelSurat.PanelSuratKetKTPSementara panelSuratKetKTPSementara1;
    private fauzi.project.panelSurat.PanelSuratKeterangan panelSuratKeterangan1;
    private fauzi.project.panelSurat.PanelSuratPernahNikah panelSuratPernahNikah1;
    private fauzi.project.panelSurat.PanelSuratRekomendasi panelSuratRekomendasi1;
    private fauzi.project.panelSurat.PanelSuratTugas panelSuratTugas1;
    private fauzi.project.panelSurat.PanelSuratketeranganKurangMampu panelSuratketeranganKurangMampu1;
    private fauzi.project.panelSurat.PanelSuratsimdanKTP panelSuratsimdanKTP1;
    private fauzi.project.panelSurat.PanelsuratKeteranganKelakuanBaik panelsuratKeteranganKelakuanBaik1;
    private fauzi.project.panelSurat.PanelsuratKeteranganTidakBerijazah panelsuratKeteranganTidakBerijazah1;
    private javax.swing.JMenuItem winclass;
    private javax.swing.JMenuItem windows;
    // End of variables declaration//GEN-END:variables
}
